Fixed concurrency crash issue
bakins/logrus-middleware pull request #6
Opened 2018-04-20 23:07 UTC by davidmahoney

Logrus-middleware crashes under load when the handler replaces a ResponseWriter from one request with one from another concurrent request.

There are a number of log lines like this:

```
2018/04/20 15:40:18 http: multiple response.WriteHeader calls
```

Followed by 

```
fatal error: concurrent map writes
```

There's probably a better way to fix it than to clone the Handler for each request, but this works so far for my purposes.

2018-04-24 11:24 UTC, bakins approved these changes

2018-04-24 11:25 UTC, bakins requested changes
This is failing tests: https://travis-ci.org/bakins/logrus-middleware/builds/369350532?utm_source=github_status&utm_medium=notification

2018-04-24 18:48 UTC, davidmahoney commented
I think the test should not be examining the top-level logging handler for the same reason that all http requests should not be writing to the top-level logging handler. I altered the test to instead examine the output buffer (as the other tests already do).

2018-04-26 21:45 UTC, bakins approved these changes

2018-04-26 21:45 UTC, merged